// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsmIKcY4uRt7qaTcMzcr-_J-F1jMG2BcQ',
    appId: '1:1066358259020:web:135b735d6518842e60e3e9',
    messagingSenderId: '1066358259020',
    projectId: 'gps-test-4ccbb',
    authDomain: 'gps-test-4ccbb.firebaseapp.com',
    storageBucket: 'gps-test-4ccbb.firebasestorage.app',
    measurementId: 'G-VRNRB5SRXW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChcBy6PknGpooeTpSw4cCzXRBUKfuXsBg',
    appId: '1:1066358259020:android:9dd2be975b7017cf60e3e9',
    messagingSenderId: '1066358259020',
    projectId: 'gps-test-4ccbb',
    storageBucket: 'gps-test-4ccbb.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsmIKcY4uRt7qaTcMzcr-_J-F1jMG2BcQ',
    appId: '1:1066358259020:web:c816d1d22ad26b8460e3e9',
    messagingSenderId: '1066358259020',
    projectId: 'gps-test-4ccbb',
    authDomain: 'gps-test-4ccbb.firebaseapp.com',
    storageBucket: 'gps-test-4ccbb.firebasestorage.app',
    measurementId: 'G-WCWNPZRS4C',
  );
}
